# Práctica 1 · Naive Bayes, K-NN y Scikit-Learn
**Fundamentos de Aprendizaje Automático 2026/2027 — Grupo 1461, pareja 10**

En esta práctica hemos programado nuestro propio Naive Bayes y nuestro propio K-NN, y los hemos comparado con las versiones de Scikit-Learn.

Usamos dos conjuntos de datos:
- **wdbc**: 569 ejemplos con 30 atributos continuos. La clase indica si el tumor es maligno (M) o benigno (B).
- **fuga_telefonia**: 10 atributos numéricos, 2 nominales (la red competidora favorita en los meses 1 y 2) y una clase binaria. Usamos el fichero `fuga_telefonia_ok.csv`.

Para que los resultados se puedan comparar, en todos los apartados hacemos lo mismo:
- **Validación simple**: la repetimos 10 veces, dejando un 30 % de los datos para test.
- **Validación cruzada**: 5 particiones (*folds*), barajando antes los datos.
- En cada caso damos el **error medio** y su **desviación típica** (en %).

In [1]:
import warnings
import numpy as np
import pandas as pd
from IPython.display import display

from MyScikitLearn.preprocesamiento import Dataset
from MyScikitLearn.particionado import ValidacionSimple, ValidacionCruzada
from MyScikitLearn.modelos.naive_bayes import ClasificadorNaiveBayes
from MyScikitLearn.modelos.knn import ClasificadorKNN
from MyScikitLearn.sklearn_utils import estrategias_sklearn, evaluar_modelo_sklearn

# Avisos de Scikit-Learn sobre intervalos vacíos al discretizar, alpha muy pequeño, etc.
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

SEMILLA = 42
DATASETS = {"WDBC": "wdbc.csv", "Fuga Telefonía": "fuga_telefonia_ok.csv"}
NUMERO_EJECUCIONES = 10   # repeticiones de la validación simple
PROPORCION_TEST = 0.3
NUMERO_PARTICIONES = 5    # folds de la validación cruzada
VALORES_K = [5, 9, 13]


def estrategias_propias():
    return {
        "Validación Simple": ValidacionSimple(proporcion_test=PROPORCION_TEST, numero_ejecuciones=NUMERO_EJECUCIONES),
        "Validación Cruzada": ValidacionCruzada(numero_particiones=NUMERO_PARTICIONES)
    }


def formatea(media, std):
    return "—" if pd.isna(media) else f"{media:.2f} ± {std:.2f}"


def tabla(df, filas, columnas):
    """Agrupa todos los resultados en una tabla con celdas 'error medio ± desviación típica' (%)."""
    df = df.copy()
    df["Error (%)"] = [formatea(m, s) for m, s in zip(df["Error Medio (%)"], df["Desviación Típica"])]
    return df.pivot_table(index=filas, columns=columnas, values="Error (%)", aggfunc="first", sort=False).fillna("")

# Apartado 1 | Naive-Bayes propio

Nuestro `ClasificadorNaiveBayes` está en `MyScikitLearn/modelos/naive_bayes.py`. En el entrenamiento calcula:
- La probabilidad a priori de cada clase (qué proporción de ejemplos hay de cada una).
- Para los atributos **nominales**: la probabilidad de cada valor dentro de cada clase, contando cuántas veces aparece. Con Laplace sumamos 1 a cada conteo.
- Para los atributos **continuos**: la media y la varianza en cada clase, porque suponemos que siguen una distribución normal.

Para clasificar, multiplicamos las probabilidades y nos quedamos con la clase más probable. En vez de multiplicar sumamos logaritmos, porque al multiplicar muchas probabilidades pequeñas el resultado puede acabar siendo 0.

Para que la comparación con y sin Laplace sea justa, las dos versiones usan las mismas particiones.

In [2]:
def evaluar_naive_bayes(nombre_dataset, ruta_dataset):
    dataset = Dataset(ruta_dataset)
    datos = dataset.obtener_datos()
    atributos_discretos = dataset.atributosDiscretos
    resultados = []
    
    for nombre_est, validador in estrategias_propias().items():
        validador.creaParticiones(len(datos))
        
        for laplace in [False, True]:
            clasificador = ClasificadorNaiveBayes(laplace=laplace)
            errores = []
            
            for particion in validador.particiones:
                datos_train = datos[particion["train"]]
                datos_test = datos[particion["test"]]
                
                clasificador.entrenamiento(datos_train, atributos_discretos, dataset.diccionarios)
                predicciones = clasificador.clasifica(datos_test, atributos_discretos, dataset.diccionarios)
                errores.append(clasificador.error(datos_test, predicciones))
            
            resultados.append({
                "Dataset": nombre_dataset,
                "Particionado": nombre_est,
                "Laplace": "Sí" if laplace else "No",
                "Error Medio (%)": np.mean(errores) * 100,
                "Desviación Típica": np.std(errores) * 100
            })
    return resultados


np.random.seed(SEMILLA)
resultados_nb = []
for nombre, ruta in DATASETS.items():
    resultados_nb += evaluar_naive_bayes(nombre, ruta)
df_nb = pd.DataFrame(resultados_nb)

print("Error de clasificación (%) del Naive Bayes propio: media ± desviación típica")
display(tabla(df_nb, ["Dataset", "Particionado"], "Laplace"))

Error de clasificación (%) del Naive Bayes propio: media ± desviación típica

Laplace                                      No            Sí
Dataset        Particionado
WDBC           Validación Simple    6.84 ± 1.61   6.84 ± 1.61
               Validación Cruzada   6.68 ± 2.12   6.68 ± 2.12
Fuga Telefonía Validación Simple   35.96 ± 3.92  35.96 ± 3.99
               Validación Cruzada  33.15 ± 3.50  33.24 ± 3.54

### Análisis de resultados (Apartado 1)

**¿Influye la corrección de Laplace?**
- En **WDBC** sale exactamente lo mismo con y sin Laplace (6,84 % en validación simple y 6,68 % en cruzada). Tiene sentido, porque todos los atributos son continuos y para ellos usamos la media y la varianza, así que Laplace no llega a usarse.
- En **Fuga Telefonía** Laplace solo afecta a los dos atributos nominales, y la diferencia es muy pequeña: 35,96 % en los dos casos con validación simple, y 33,15 % frente a 33,24 % en cruzada. Creemos que es porque estos atributos solo tienen 6 valores y hay muchos ejemplos de cada clase, así que todos los valores aparecen en el entrenamiento y ninguna probabilidad sale 0. Sumar 1 a conteos de cientos casi no cambia nada.
- Laplace sería importante si algún valor no apareciera en el train para alguna clase. Sin corrección esa probabilidad sería 0 y, al multiplicar, toda la probabilidad de esa clase sería 0 aunque el resto de atributos dijeran lo contrario. (En nuestro código, para no calcular log(0), ponemos 1e-10 en su lugar, pero el efecto es casi el mismo.) Esto pasaría más con pocos datos o con atributos que tengan muchos valores distintos.

**¿Cómo funciona en cada conjunto?**
En WDBC el error es bajo (alrededor del 6,7–6,8 %), así que parece que los dos tipos de tumor se distinguen bien. En Fuga Telefonía el error es mucho mayor (33–36 %). Mirando los datos vimos que algunos atributos no se parecen nada a una normal: por ejemplo, *Total Data Consumption* va desde casi 0 hasta unos 100 millones. También hay atributos relacionados entre sí (el gasto total y los gastos *on-net*/*off-net*), y Naive Bayes supone que los atributos son independientes. Pensamos que por eso le cuesta más.

**¿Cambia algo entre validación simple y cruzada?**
En WDBC dan casi lo mismo (6,84 ± 1,61 % y 6,68 ± 2,12 %). En Fuga Telefonía la cruzada da algo menos de error (33,2 % frente a 36,0 %), pero la diferencia es más pequeña que la desviación típica (3,5–4 puntos), así que no podemos decir que una sea mejor que la otra. Una posible explicación es que en la cruzada se entrena con el 80 % de los datos y en la simple con el 70 %.

# Apartado 2 | Naive-Bayes con Scikit-Learn

Repetimos lo mismo con Scikit-Learn. Para las particiones usamos `ShuffleSplit` (10 repeticiones, 30 % test) como validación simple y `KFold` (5 *folds*, `shuffle=True`) como validación cruzada, siempre con la misma semilla para que todos los modelos usen las mismas particiones.

Modelos que hemos probado:
- `GaussianNB`: trata todos los atributos como normales. No tiene Laplace.
- `MultinomialNB` y `CategoricalNB`, con `alpha=1` (Laplace) y sin Laplace. Para "sin Laplace" pusimos `alpha=1e-10`, porque con `alpha=0` Scikit-Learn avisa de que pueden salir logaritmos de 0.
- `CategoricalNB + discretización`: al ver que `CategoricalNB` fallaba (lo explicamos más abajo), probamos a dividir antes cada atributo continuo en 10 intervalos con `KBinsDiscretizer`, para que todos los atributos sean categorías.

In [3]:
from sklearn.naive_bayes import MultinomialNB, GaussianNB, CategoricalNB
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import KBinsDiscretizer

ALPHAS = {"No": 1e-10, "Sí": 1.0}
NUM_INTERVALOS = 10
# CategoricalNB crea una categoría por cada entero entre 0 y el valor máximo del atributo.
# Si el máximo es enorme se queda sin memoria, así que en ese caso no lo ejecutamos.
MAX_CATEGORIAS = 100_000


def categorical_discretizado(atributos_discretos, alpha):
    # Dividimos cada atributo continuo en 10 intervalos y los nominales se quedan igual
    continuos = [i for i, discreto in enumerate(atributos_discretos) if not discreto]
    discretizador = ColumnTransformer(
        [("intervalos", KBinsDiscretizer(n_bins=NUM_INTERVALOS, encode="ordinal", strategy="quantile"), continuos)],
        remainder="passthrough")
    return make_pipeline(discretizador, CategoricalNB(alpha=alpha, min_categories=NUM_INTERVALOS))


def evaluar_nb_sklearn(nombre_dataset, ruta_dataset):
    dataset = Dataset(ruta_dataset)
    datos = dataset.obtener_datos()
    X, y = datos[:, :-1], datos[:, -1]
    discretos = dataset.atributosDiscretos
    resultados = []

    # (modelo, laplace, función que crea el modelo)
    configuraciones = [("GaussianNB", "N/A", lambda: GaussianNB())]
    for laplace, alpha in ALPHAS.items():
        configuraciones.append(("MultinomialNB", laplace, lambda alpha=alpha: MultinomialNB(alpha=alpha)))
        configuraciones.append(("CategoricalNB", laplace, lambda alpha=alpha: CategoricalNB(alpha=alpha)))
        configuraciones.append(("CategoricalNB + discretización", laplace,
                                lambda alpha=alpha: categorical_discretizado(discretos, alpha)))

    for nombre_est, particionado in estrategias_sklearn(SEMILLA, NUMERO_EJECUCIONES, PROPORCION_TEST, NUMERO_PARTICIONES).items():
        for modelo, laplace, crear in configuraciones:
            if modelo == "CategoricalNB" and X.max() >= MAX_CATEGORIAS:
                media, std = np.nan, np.nan
                incidencia = f"No ejecutado: un atributo llega a {X.max():.0f}, harían falta demasiadas categorías"
            else:
                media, std, incidencia = evaluar_modelo_sklearn(crear, X, y, particionado)
            resultados.append({
                "Dataset": nombre_dataset,
                "Particionado": nombre_est,
                "Modelo": modelo,
                "Laplace": laplace,
                "Error Medio (%)": media,
                "Desviación Típica": std,
                "Incidencia": incidencia
            })
    return resultados


resultados_nb_sk = []
for nombre, ruta in DATASETS.items():
    resultados_nb_sk += evaluar_nb_sklearn(nombre, ruta)
df_nb_sk = pd.DataFrame(resultados_nb_sk)

print("Error de clasificación (%) de Naive Bayes con Scikit-Learn: media ± desviación típica")
display(tabla(df_nb_sk, ["Dataset", "Particionado", "Modelo"], "Laplace"))

print("Modelos que no han podido evaluarse (—):")
incidencias = df_nb_sk[df_nb_sk["Incidencia"] != ""]
display(incidencias[["Dataset", "Particionado", "Modelo", "Laplace", "Incidencia"]])

Error de clasificación (%) de Naive Bayes con Scikit-Learn: media ± desviación típica

Laplace                                                                    N/A  \
Dataset        Particionado       Modelo
WDBC           Validación Simple  GaussianNB                       5.56 ± 1.39
                                  MultinomialNB
                                  CategoricalNB
                                  CategoricalNB + discretización
               Validación Cruzada GaussianNB                       6.15 ± 2.01
                                  MultinomialNB
                                  CategoricalNB
                                  CategoricalNB + discretización
Fuga Telefonía Validación Simple  GaussianNB                      42.01 ± 3.26
                                  MultinomialNB
                                  CategoricalNB
                                  CategoricalNB + discretización
               Validación Cruzada GaussianNB                      39.44 ± 5.70
                                  MultinomialNB
                                  CategoricalNB
                                  CategoricalNB + discretización

Laplace                                                                     No  \
Dataset        Particionado       Modelo
WDBC           Validación Simple  GaussianNB
                                  MultinomialNB                   10.18 ± 1.34
                                  CategoricalNB                              —
                                  CategoricalNB + discretización   4.80 ± 1.92
               Validación Cruzada GaussianNB
                                  MultinomialNB                   10.37 ± 2.92
                                  CategoricalNB                              —
                                  CategoricalNB + discretización   5.27 ± 2.42
Fuga Telefonía Validación Simple  GaussianNB
                                  MultinomialNB                              —
                                  CategoricalNB                              —
                                  CategoricalNB + discretización  23.86 ± 1.60
               Validación Cruzada GaussianNB
                                  MultinomialNB                              —
                                  CategoricalNB                              —
                                  CategoricalNB + discretización  24.54 ± 0.59

Laplace                                                                     Sí
Dataset        Particionado       Modelo
WDBC           Validación Simple  GaussianNB
                                  MultinomialNB                   10.18 ± 1.34
                                  CategoricalNB                              —
                                  CategoricalNB + discretización   4.91 ± 1.74
               Validación Cruzada GaussianNB
                                  MultinomialNB                   10.37 ± 2.92
                                  CategoricalNB                              —
                                  CategoricalNB + discretización   5.62 ± 2.33
Fuga Telefonía Validación Simple  GaussianNB
                                  MultinomialNB                              —
                                  CategoricalNB                              —
                                  CategoricalNB + discretización  23.98 ± 1.79
               Validación Cruzada GaussianNB
                                  MultinomialNB                              —
                                  CategoricalNB                              —
                                  CategoricalNB + discretización  24.35 ± 0.37

Modelos que no han podido evaluarse (—):

,Dataset,Particionado,Modelo,Laplace,Incidencia
2,WDBC,Validación Simple,CategoricalNB,No,IndexError: index 4 is out of bounds for axis ...
5,WDBC,Validación Simple,CategoricalNB,Sí,IndexError: index 4 is out of bounds for axis ...
9,WDBC,Validación Cruzada,CategoricalNB,No,IndexError: index 1 is out of bounds for axis ...
12,WDBC,Validación Cruzada,CategoricalNB,Sí,IndexError: index 1 is out of bounds for axis ...
15,Fuga Telefonía,Validación Simple,MultinomialNB,No,ValueError: Negative values in data passed to ...
16,Fuga Telefonía,Validación Simple,CategoricalNB,No,"No ejecutado: un atributo llega a 99456402, ha..."
18,Fuga Telefonía,Validación Simple,MultinomialNB,Sí,ValueError: Negative values in data passed to ...
19,Fuga Telefonía,Validación Simple,CategoricalNB,Sí,"No ejecutado: un atributo llega a 99456402, ha..."
22,Fuga Telefonía,Validación Cruzada,MultinomialNB,No,ValueError: Negative values in data passed to ...
23,Fuga Telefonía,Validación Cruzada,CategoricalNB,No,"No ejecutado: un atributo llega a 99456402, ha..."
25,Fuga Telefonía,Validación Cruzada,MultinomialNB,Sí,ValueError: Negative values in data passed to ...
26,Fuga Telefonía,Validación Cruzada,CategoricalNB,Sí,"No ejecutado: un atributo llega a 99456402, ha..."

Queríamos entender por qué falla `CategoricalNB`. Según la documentación, este modelo espera que cada atributo sea un número entero que representa una categoría (0, 1, 2…). Así que miramos qué pasa con nuestros datos al convertirlos a enteros:

In [4]:
# Pasamos los atributos a entero, como hace CategoricalNB, y miramos qué ocurre
for nombre, ruta in DATASETS.items():
    X = Dataset(ruta).obtener_datos()[:, :-1]
    X_enteros = X.astype(int)

    constantes = 0
    for j in range(X.shape[1]):
        if X_enteros[:, j].min() == X_enteros[:, j].max():
            constantes += 1

    print(f"{nombre}: {constantes} de {X.shape[1]} atributos se quedan con un único valor al pasarlos a entero")
    print(f"    valor más grande: {X_enteros.max()} (CategoricalNB necesitaría {X_enteros.max() + 1} categorías)")

WDBC: 16 de 30 atributos se quedan con un único valor al pasarlos a entero
    valor más grande: 4254 (CategoricalNB necesitaría 4255 categorías)
Fuga Telefonía: 0 de 12 atributos se quedan con un único valor al pasarlos a entero
    valor más grande: 99456402 (CategoricalNB necesitaría 99456403 categorías)

### Análisis comparativo de los métodos de Scikit-Learn (Apartado 2)

**`GaussianNB`.** En WDBC hace lo mismo que nuestro Naive Bayes (todos los atributos son continuos) y los errores son parecidos: 5,56 % y 6,15 % frente a nuestros 6,84 % y 6,68 %. Las diferencias son menores que la desviación típica, y creemos que vienen de que las particiones no son las mismas que las nuestras. En Fuga Telefonía es unos 6 puntos peor que el nuestro (42,0 % y 39,4 % frente a 36,0 % y 33,2 %). La explicación que encontramos es que `GaussianNB` trata también los dos atributos nominales como números con una distribución normal, cuando en realidad los códigos 0…5 son solo nombres de compañías y no tiene sentido calcular su media.

**`MultinomialNB`.** Este modelo está pensado para conteos (por ejemplo, cuántas veces aparece cada palabra en un texto), no para medidas como las nuestras. En WDBC es el peor (≈ 10,2–10,4 %), y Laplace no cambia nada porque los valores son tan grandes que sumar 1 no se nota. **En Fuga Telefonía no se puede ejecutar**: da el error `ValueError: Negative values`. Al buscar por qué, vimos que *network_age* y *Customer tenure in month* tienen algunos valores negativos (−5 y −0,17), lo cual no tiene sentido para una antigüedad, así que deben ser errores en los datos.

**`CategoricalNB`.** Sí da problemas, en los dos conjuntos, porque supone que **todos** los atributos son categorías (enteros 0, 1, 2…) y los nuestros son casi todos continuos:
1. Convierte cada valor a entero quitando los decimales. En WDBC **16 de los 30 atributos** tienen todos sus valores entre 0 y 1, así que se quedan todos en 0 y se pierde su información.
2. Cada entero distinto lo trata como una categoría distinta. Si en el test aparece un valor que no estaba en el train, `predict` falla con `IndexError`, que es lo que nos pasó en WDBC.
3. En Fuga Telefonía ni siquiera lo hemos ejecutado: *Total Data Consumption* llega a 99.456.402, así que tendría que crear casi 100 millones de categorías.

**`CategoricalNB + discretización`.** Al dividir cada atributo continuo en 10 intervalos, todos los atributos pasan a ser categorías de verdad y el modelo ya funciona. Nos sorprendió que es el que mejor resultado da de todos los Naive Bayes, sobre todo en Fuga Telefonía (alrededor del 24 %). Nuestra idea es que así no hace falta suponer que los datos siguen una normal, y en Fuga Telefonía está claro que no la siguen.

# Apartado 3 | K-NN propio

Nuestro `ClasificadorKNN` está en `MyScikitLearn/modelos/knn.py`. Entrenar solo consiste en guardar los datos de entrenamiento. Para clasificar un ejemplo calculamos su distancia euclídea a todos los ejemplos guardados, cogemos los $K$ más cercanos y predecimos la clase que más se repite entre ellos. Como $K$ es impar y solo hay dos clases, no puede haber empate.

### Estandarización: `Dataset.estandarizarDatos(media=True, std=True)`
Decidimos poner la estandarización como un método de la clase **`Dataset`** (en `MyScikitLearn/preprocesamiento.py`) por estos motivos:
- Es un cambio en los datos, no en el algoritmo, y los datos los guarda `Dataset`.
- `Dataset` ya sabe qué atributos son nominales gracias a los diccionarios. Esos no hay que estandarizarlos (sus códigos 0, 1, 2… no son cantidades), y la clase tampoco.
- Así se puede usar con cualquier clasificador, no solo con K-NN.

A cada atributo continuo le restamos la media y lo dividimos entre la desviación típica. Para comprobar que lo hacíamos bien, lo comparamos con `StandardScaler` de Scikit-Learn. Al principio no salía igual, y vimos que `StandardScaler` calcula la desviación típica dividiendo entre $n$ (`ddof=0`), así que lo cambiamos para hacer lo mismo:

In [5]:
from sklearn.preprocessing import StandardScaler

for nombre, ruta in DATASETS.items():
    dataset = Dataset(ruta)
    continuos = [not discreto for discreto in dataset.atributosDiscretos]
    X_sklearn = StandardScaler().fit_transform(dataset.obtener_datos()[:, :-1][:, continuos])
    dataset.estandarizarDatos(media=True, std=True)
    X_propio = dataset.obtener_datos()[:, :-1][:, continuos]
    print(f"{nombre}: diferencia máxima con StandardScaler = {np.abs(X_propio - X_sklearn).max():.2e}")

WDBC: diferencia máxima con StandardScaler = 0.00e+00
Fuga Telefonía: diferencia máxima con StandardScaler = 0.00e+00

In [6]:
def evaluar_knn_propio(nombre_dataset, ruta_dataset):
    datos_originales = Dataset(ruta_dataset)
    datos_estandarizados = Dataset(ruta_dataset)
    datos_estandarizados.estandarizarDatos(media=True, std=True)
    versiones = {"No": datos_originales, "Sí": datos_estandarizados}
    resultados = []
    
    for nombre_est, validador in estrategias_propias().items():
        # Mismas particiones con y sin estandarizar y para todos los K
        validador.creaParticiones(len(datos_originales.datos_numericos))
        
        for estandarizado, dataset in versiones.items():
            datos = dataset.obtener_datos()
            
            for k in VALORES_K:
                clasificador = ClasificadorKNN(k=k)
                errores = []
                
                for particion in validador.particiones:
                    datos_train = datos[particion["train"]]
                    datos_test = datos[particion["test"]]
                    
                    clasificador.entrenamiento(datos_train, dataset.atributosDiscretos, dataset.diccionarios)
                    predicciones = clasificador.clasifica(datos_test, dataset.atributosDiscretos, dataset.diccionarios)
                    errores.append(clasificador.error(datos_test, predicciones))
                
                resultados.append({
                    "Dataset": nombre_dataset,
                    "Particionado": nombre_est,
                    "Estandarizado": estandarizado,
                    "K": k,
                    "Error Medio (%)": np.mean(errores) * 100,
                    "Desviación Típica": np.std(errores) * 100
                })
    return resultados


np.random.seed(SEMILLA)
resultados_knn = []
for nombre, ruta in DATASETS.items():
    resultados_knn += evaluar_knn_propio(nombre, ruta)
df_knn = pd.DataFrame(resultados_knn)

print("Error de clasificación (%) del K-NN propio (distancia euclídea): media ± desviación típica")
display(tabla(df_knn, ["Dataset", "Particionado", "Estandarizado"], "K"))

Error de clasificación (%) del K-NN propio (distancia euclídea): media ± desviación típica

K                                                          5             9   \
Dataset        Particionado       Estandarizado
WDBC           Validación Simple  No              7.43 ± 1.50   7.08 ± 1.15
                                  Sí              4.62 ± 1.37   4.33 ± 1.26
               Validación Cruzada No              7.03 ± 2.00   6.85 ± 1.28
                                  Sí              3.52 ± 1.57   3.17 ± 1.54
Fuga Telefonía Validación Simple  No             38.86 ± 1.72  39.07 ± 2.13
                                  Sí             31.05 ± 2.54  30.34 ± 1.86
               Validación Cruzada No             38.89 ± 4.01  37.13 ± 3.64
                                  Sí             30.93 ± 2.61  31.57 ± 3.25

K                                                          13
Dataset        Particionado       Estandarizado
WDBC           Validación Simple  No              7.49 ± 1.04
                                  Sí              4.85 ± 1.20
               Validación Cruzada No              6.50 ± 1.42
                                  Sí              3.52 ± 2.56
Fuga Telefonía Validación Simple  No             39.14 ± 2.20
                                  Sí             31.23 ± 2.37
               Validación Cruzada No             37.96 ± 4.54
                                  Sí             31.48 ± 4.65

### Análisis de resultados (Apartado 3)

**¿Influye estandarizar?** Es lo que más cambia los resultados. La distancia euclídea suma las diferencias al cuadrado de todos los atributos, así que si uno tiene valores muy grandes es el que manda. Por ejemplo, en WDBC *area* va de cientos a miles y *smoothness* son décimas, y en Fuga Telefonía *Total Data Consumption* llega a millones. Sin estandarizar, los vecinos se eligen casi solo por esos atributos. Al estandarizar, todos tienen la misma escala:
- En **WDBC** el error baja de 6,5–7,5 % a 3,2–4,9 %, más o menos la mitad.
- En **Fuga Telefonía** baja de 37–39 % a 30,3–31,6 %, unos 7–8 puntos.

Esto pasa para todos los $K$ y con las dos validaciones.

**¿Influye $K$ (5, 9, 13)?** Mucho menos que estandarizar. En WDBC estandarizado el mejor es $K=9$ con las dos validaciones (4,33 % y 3,17 %), pero la diferencia con $K=5$ y $K=13$ es de pocas décimas, menos que la desviación típica (1,2–2,6 puntos). En Fuga Telefonía estandarizado todos están entre 30,3 % y 31,6 %, así que no hay uno claramente mejor. Por lo que vimos en clase, con un $K$ pequeño el modelo se fija en muy pocos vecinos y un punto raro puede hacer que se equivoque, y con un $K$ grande la decisión es más "suave". Con nuestros datos, entre 5 y 13 apenas se nota.

**¿Y la validación?** En WDBC estandarizado la cruzada da menos error que la simple (3,2–3,5 % frente a 4,3–4,9 %). Creemos que es porque K-NN funciona mejor cuantos más ejemplos tiene para comparar, y en la cruzada entrena con el 80 % de los datos en vez del 70 %. En Fuga Telefonía las dos dan resultados parecidos.

# Apartado 4 | K-NN con Scikit-Learn

Usamos `KNeighborsClassifier(n_neighbors=K, metric="euclidean")` con los mismos $K$ y las mismas validaciones (`ShuffleSplit` y `KFold`). Para estandarizar usamos `StandardScaler` dentro de un `Pipeline`, solo sobre los atributos numéricos, igual que en nuestra versión.

Hay una diferencia: dentro del `Pipeline`, `StandardScaler` calcula la media y la desviación típica solo con el train de cada partición, mientras que nuestra `estandarizarDatos` la aplicamos a todos los datos antes de hacer las particiones, como pide el enunciado. Esto puede hacer que los resultados cambien un poco.

In [7]:
from sklearn.neighbors import KNeighborsClassifier


def crear_knn_sklearn(k, estandarizar, atributos_discretos):
    knn = KNeighborsClassifier(n_neighbors=k, metric="euclidean")
    if not estandarizar:
        return knn
    continuos = [i for i, discreto in enumerate(atributos_discretos) if not discreto]
    escalado = ColumnTransformer([("estandarizar", StandardScaler(), continuos)], remainder="passthrough")
    return make_pipeline(escalado, knn)


def evaluar_knn_sklearn(nombre_dataset, ruta_dataset):
    dataset = Dataset(ruta_dataset)
    datos = dataset.obtener_datos()
    X, y = datos[:, :-1], datos[:, -1]
    resultados = []
    
    for nombre_est, particionado in estrategias_sklearn(SEMILLA, NUMERO_EJECUCIONES, PROPORCION_TEST, NUMERO_PARTICIONES).items():
        for estandarizado in ["No", "Sí"]:
            for k in VALORES_K:
                crear = lambda: crear_knn_sklearn(k, estandarizado == "Sí", dataset.atributosDiscretos)
                media, std, _ = evaluar_modelo_sklearn(crear, X, y, particionado)
                resultados.append({
                    "Dataset": nombre_dataset,
                    "Particionado": nombre_est,
                    "Estandarizado": estandarizado,
                    "K": k,
                    "Error Medio (%)": media,
                    "Desviación Típica": std
                })
    return resultados


resultados_knn_sk = []
for nombre, ruta in DATASETS.items():
    resultados_knn_sk += evaluar_knn_sklearn(nombre, ruta)
df_knn_sk = pd.DataFrame(resultados_knn_sk)

print("Error de clasificación (%) de KNeighborsClassifier (distancia euclídea): media ± desviación típica")
display(tabla(df_knn_sk, ["Dataset", "Particionado", "Estandarizado"], "K"))

Error de clasificación (%) de KNeighborsClassifier (distancia euclídea): media ± desviación típica

K                                                          5             9   \
Dataset        Particionado       Estandarizado
WDBC           Validación Simple  No              6.08 ± 1.51   6.08 ± 1.66
                                  Sí              3.45 ± 1.49   3.63 ± 1.40
               Validación Cruzada No              6.33 ± 2.81   7.03 ± 3.89
                                  Sí              4.05 ± 1.91   3.52 ± 2.02
Fuga Telefonía Validación Simple  No             38.15 ± 2.35  36.48 ± 2.08
                                  Sí             31.42 ± 1.14  30.93 ± 1.55
               Validación Cruzada No             37.78 ± 1.80  36.67 ± 1.84
                                  Sí             32.87 ± 0.93  31.67 ± 1.12

K                                                          13
Dataset        Particionado       Estandarizado
WDBC           Validación Simple  No              6.32 ± 1.30
                                  Sí              3.74 ± 1.80
               Validación Cruzada No              6.33 ± 4.25
                                  Sí              4.22 ± 1.18
Fuga Telefonía Validación Simple  No             37.65 ± 2.09
                                  Sí             31.33 ± 1.86
               Validación Cruzada No             37.31 ± 1.57
                                  Sí             30.46 ± 3.19

### Análisis de resultados (Apartado 4)

**Estandarizar.** Pasa lo mismo que con nuestro K-NN: en WDBC el error baja de 6,1–7,0 % a 3,5–4,2 %, y en Fuga Telefonía de 36,5–38,2 % a 30,5–32,9 %. Así que no es algo de nuestra implementación, sino de cómo funciona K-NN con la distancia euclídea.

**Valor de $K$.** Otra vez las diferencias suelen ser pequeñas (menos de 1 punto con datos estandarizados) y no siempre gana el mismo. En WDBC el mejor es $K=5$ con validación simple y $K=9$ con cruzada, y en Fuga Telefonía $K=9$ con simple y $K=13$ con cruzada. El caso con más diferencia es Fuga Telefonía con validación cruzada, donde $K=13$ (30,46 %) mejora en unos 2,4 puntos a $K=5$ (32,87 %), pero la desviación típica con $K=13$ también es alta (3,19 puntos), así que no lo vemos como una diferencia clara.

**Comparación con nuestra versión.** Los errores son muy parecidos a los nuestros. Scikit-Learn es bastante más rápido (nuestro bucle calcula todas las distancias para cada ejemplo de test), pero los vecinos más cercanos deberían ser los mismos. Creemos que las diferencias se deben a que las particiones no son exactamente las mismas.

# Apartado 5 | Conclusión

Ponemos juntos los resultados de nuestras implementaciones y los de Scikit-Learn para compararlos.

In [8]:
# Naive Bayes: implementación propia frente a los modelos de Scikit-Learn (con Laplace cuando aplica)
nb_propio = df_nb.assign(Método="Propio (Laplace " + df_nb["Laplace"] + ")")
nb_sklearn = df_nb_sk[df_nb_sk["Laplace"] != "No"].assign(Método=lambda d: "SK " + d["Modelo"])
print("Naive Bayes · error (%): propio frente a Scikit-Learn")
display(tabla(pd.concat([nb_propio, nb_sklearn]), ["Dataset", "Particionado"], "Método").T)

# K-NN: implementación propia frente a KNeighborsClassifier
indice_knn = ["Dataset", "Particionado", "Estandarizado", "K"]
knn = pd.concat([df_knn.assign(Implementación="Propia"), df_knn_sk.assign(Implementación="Scikit-Learn")])
comparativa_knn = tabla(knn, indice_knn, "Implementación")
medias_knn = knn.pivot_table(index=indice_knn, columns="Implementación", values="Error Medio (%)", sort=False)
comparativa_knn["Diferencia (p.p.)"] = (medias_knn["Propia"] - medias_knn["Scikit-Learn"]).round(2)
print("K-NN · error (%): propio frente a Scikit-Learn")
display(comparativa_knn)

Naive Bayes · error (%): propio frente a Scikit-Learn

Dataset                                        WDBC                     \
Particionado                      Validación Simple Validación Cruzada
Método
Propio (Laplace No)                     6.84 ± 1.61        6.68 ± 2.12
Propio (Laplace Sí)                     6.84 ± 1.61        6.68 ± 2.12
SK GaussianNB                           5.56 ± 1.39        6.15 ± 2.01
SK MultinomialNB                       10.18 ± 1.34       10.37 ± 2.92
SK CategoricalNB                                  —                  —
SK CategoricalNB + discretización       4.91 ± 1.74        5.62 ± 2.33

Dataset                              Fuga Telefonía
Particionado                      Validación Simple Validación Cruzada
Método
Propio (Laplace No)                    35.96 ± 3.92       33.15 ± 3.50
Propio (Laplace Sí)                    35.96 ± 3.99       33.24 ± 3.54
SK GaussianNB                          42.01 ± 3.26       39.44 ± 5.70
SK MultinomialNB                                  —                  —
SK CategoricalNB                                  —                  —
SK CategoricalNB + discretización      23.98 ± 1.79       24.35 ± 0.37

K-NN · error (%): propio frente a Scikit-Learn

Implementación                                            Propia  \
Dataset        Particionado       Estandarizado K
WDBC           Validación Simple  No            5    7.43 ± 1.50
                                                9    7.08 ± 1.15
                                                13   7.49 ± 1.04
                                  Sí            5    4.62 ± 1.37
                                                9    4.33 ± 1.26
                                                13   4.85 ± 1.20
               Validación Cruzada No            5    7.03 ± 2.00
                                                9    6.85 ± 1.28
                                                13   6.50 ± 1.42
                                  Sí            5    3.52 ± 1.57
                                                9    3.17 ± 1.54
                                                13   3.52 ± 2.56
Fuga Telefonía Validación Simple  No            5   38.86 ± 1.72
                                                9   39.07 ± 2.13
                                                13  39.14 ± 2.20
                                  Sí            5   31.05 ± 2.54
                                                9   30.34 ± 1.86
                                                13  31.23 ± 2.37
               Validación Cruzada No            5   38.89 ± 4.01
                                                9   37.13 ± 3.64
                                                13  37.96 ± 4.54
                                  Sí            5   30.93 ± 2.61
                                                9   31.57 ± 3.25
                                                13  31.48 ± 4.65

Implementación                                      Scikit-Learn  \
Dataset        Particionado       Estandarizado K
WDBC           Validación Simple  No            5    6.08 ± 1.51
                                                9    6.08 ± 1.66
                                                13   6.32 ± 1.30
                                  Sí            5    3.45 ± 1.49
                                                9    3.63 ± 1.40
                                                13   3.74 ± 1.80
               Validación Cruzada No            5    6.33 ± 2.81
                                                9    7.03 ± 3.89
                                                13   6.33 ± 4.25
                                  Sí            5    4.05 ± 1.91
                                                9    3.52 ± 2.02
                                                13   4.22 ± 1.18
Fuga Telefonía Validación Simple  No            5   38.15 ± 2.35
                                                9   36.48 ± 2.08
                                                13  37.65 ± 2.09
                                  Sí            5   31.42 ± 1.14
                                                9   30.93 ± 1.55
                                                13  31.33 ± 1.86
               Validación Cruzada No            5   37.78 ± 1.80
                                                9   36.67 ± 1.84
                                                13  37.31 ± 1.57
                                  Sí            5   32.87 ± 0.93
                                                9   31.67 ± 1.12
                                                13  30.46 ± 3.19

Implementación                                      Diferencia (p.p.)
Dataset        Particionado       Estandarizado K
WDBC           Validación Simple  No            5                1.35
                                                9                0.99
                                                13               1.17
                                  Sí            5                1.17
                                                9                0.70
                                                13               1.11
               Validación Cruzada No            5                0.70
                                                9               -0.18
                                                13               0.17
                                  Sí            5               -0.53
                                                9               -0.36
                                                13              -0.70
Fuga Telefonía Validación Simple  No            5                0.71
                                                9                2.59
                                                13               1.48
                                  Sí            5               -0.37
                                                9               -0.59
                                                13              -0.09
               Validación Cruzada No            5                1.11
                                                9                0.46
                                                13               0.65
                                  Sí            5               -1.94
                                                9               -0.09
                                                13               1.02

In [9]:
# Resumen: mejor configuración de cada algoritmo e implementación (validación cruzada)
todos = pd.concat([
    df_nb.assign(Algoritmo="Naive Bayes", Implementación="Propia",
                 Configuración="Laplace " + df_nb["Laplace"]),
    df_nb_sk.assign(Algoritmo="Naive Bayes", Implementación="Scikit-Learn",
                    Configuración=df_nb_sk["Modelo"] + " (Laplace " + df_nb_sk["Laplace"] + ")"),
    df_knn.assign(Algoritmo="K-NN", Implementación="Propia",
                  Configuración="K=" + df_knn["K"].astype(str) + ", estandarizado " + df_knn["Estandarizado"]),
    df_knn_sk.assign(Algoritmo="K-NN", Implementación="Scikit-Learn",
                     Configuración="K=" + df_knn_sk["K"].astype(str) + ", estandarizado " + df_knn_sk["Estandarizado"]),
], ignore_index=True)

cruzada = todos[todos["Particionado"] == "Validación Cruzada"].dropna(subset=["Error Medio (%)"])
mejores = cruzada.loc[cruzada.groupby(["Dataset", "Algoritmo", "Implementación"], sort=False)["Error Medio (%)"].idxmin()]
mejores = mejores.assign(**{"Error (%)": [formatea(m, s) for m, s in zip(mejores["Error Medio (%)"], mejores["Desviación Típica"])]})
print("Mejor configuración por conjunto, algoritmo e implementación (validación cruzada)")
display(mejores.set_index(["Dataset", "Algoritmo", "Implementación"])[["Configuración", "Error (%)"]])

Mejor configuración por conjunto, algoritmo e implementación (validación cruzada)

,,,Configuración,Error (%)
Dataset,Algoritmo,Implementación,,
WDBC,Naive Bayes,Propia,Laplace No,6.68 ± 2.12
Fuga Telefonía,Naive Bayes,Propia,Laplace No,33.15 ± 3.50
WDBC,Naive Bayes,Scikit-Learn,CategoricalNB + discretización (Laplace No),5.27 ± 2.42
Fuga Telefonía,Naive Bayes,Scikit-Learn,CategoricalNB + discretización (Laplace Sí),24.35 ± 0.37
WDBC,K-NN,Propia,"K=9, estandarizado Sí",3.17 ± 1.54
Fuga Telefonía,K-NN,Propia,"K=5, estandarizado Sí",30.93 ± 2.61
WDBC,K-NN,Scikit-Learn,"K=9, estandarizado Sí",3.52 ± 2.02
Fuga Telefonía,K-NN,Scikit-Learn,"K=13, estandarizado Sí",30.46 ± 3.19

### Conclusiones

**Nuestras implementaciones frente a Scikit-Learn.**
- **K-NN**: con datos estandarizados, la diferencia entre nuestro K-NN y `KNeighborsClassifier` va de −1,9 a +1,2 puntos y de media es casi 0 (≈ −0,1). Sin estandarizar, el nuestro sale de media ≈ 0,9 puntos peor. Son diferencias del tamaño de la desviación típica, y pensamos que vienen de que las particiones son distintas y de que `StandardScaler` solo usa el train.
- **Naive Bayes**: en WDBC nuestro Naive Bayes y `GaussianNB` dan errores parecidos, lo que nos da confianza en que nuestra implementación está bien. En Fuga Telefonía el nuestro es mejor que `GaussianNB` porque trata los atributos nominales como categorías.

**Sobre Naive Bayes.** Hemos aprendido que hay que elegir el modelo según el tipo de atributos. `MultinomialNB` (pensado para conteos) y `CategoricalNB` usado directamente no sirven con atributos continuos: el primero es el peor en WDBC y falla en Fuga Telefonía por los valores negativos, y el segundo falla en los dos conjuntos. Lo que mejor ha funcionado es **discretizar y usar `CategoricalNB`**, que mejora a nuestro Naive Bayes en los dos conjuntos (5,3 % frente a 6,7 % en WDBC y 24,4 % frente a 33,2 % en Fuga Telefonía, con validación cruzada). Creemos que es porque no obliga a que los datos sigan una normal. Laplace casi no ha cambiado nada en nuestros experimentos, porque en WDBC no se usa y en Fuga Telefonía todos los valores nominales aparecen en las dos clases.

**Sobre K-NN.** Con la distancia euclídea hay que estandarizar: el error baja a la mitad en WDBC y unos 7–8 puntos en Fuga Telefonía. El valor de $K$ influye mucho menos.

**Por conjunto de datos.**
- **WDBC**: el mejor es el **K-NN estandarizado** (3,2 % con nuestra implementación y $K=9$; 3,5 % con Scikit-Learn), mejor que cualquier Naive Bayes (≥ 4,8 %).
- **Fuga Telefonía**: es mucho más difícil para los dos algoritmos. El K-NN estandarizado (≈ 30,5–31 %) mejora a nuestro Naive Bayes (≈ 33 %), pero lo mejor ha sido el **Naive Bayes con atributos discretizados** (≈ 24 %). También hemos visto que tiene valores imposibles (antigüedades negativas), que habría que limpiar igual que se hizo con las filas eliminadas en `fuga_telefonia_ok.csv`.